--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/VanillaPickBlock
branches:
  - main
projects:
  VanillaPickBlock:
    icon: "assets/icon.png"
    lint:
      phpstan: false
...
