--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/VanillaPickBlock
branches:
  - master
projects:
  VanillaPickBlock:
    icon: "icon.png"
    lint:
      phpstan: false
...
